#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Mutt-Addressbook
version:      0.05
version_from: mph
installdirs:  site
requires:
    Class::MethodMaker:            1.1
    XML::Simple:                   2.00

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
